#pragma once

#define GRID_SIZE (50)
#define CHESS_BOARD_ROW_COUNT (10)
#define CHESS_BOARD_COLUMN_COUNT (9)
#define CHESS_BOARD_HIGHT ((CHESS_BOARD_ROW_COUNT - 1) * GRID_SIZE)
#define CHESS_BOARD_WIDTH ((CHESS_BOARD_COLUMN_COUNT - 1) * GRID_SIZE)
